"""6x6 bitmap font for the WS2812b block display.

Each glyph is 6 strings of 6 characters, top row first. 'X' (or any
non-'.' character) means lit; '.' means dark. One glyph fills one 6x6 block.

Most letters occupy columns 1-4, leaving a blank column on each side. The
wide ones -- M, N, V, W, X, Y, Z and a few symbols -- spill into column 0 to
stay legible.

Capitals fill all six rows. Lowercase is bottom-justified: glyphs sit on row
5, so they share a baseline with the capitals. The exceptions are the
descenders g j p q y, whose tails occupy row 5 and whose bodies therefore sit
one row higher -- a 6-row cell cannot put a tail below a row-5 baseline.

This module only describes shapes. Orientation, block ordering and colour
are handled by text6x6.py.
"""

WIDTH = 6
HEIGHT = 6

BLANK = ("......",) * HEIGHT

GLYPHS = {
    " ": BLANK,

    # --- letters ---------------------------------------------------------
    "A": ("..XX..",
          ".X..X.",
          ".X..X.",
          ".XXXX.",
          ".X..X.",
          ".X..X."),
    "B": (".XXX..",
          ".X..X.",
          ".XXX..",
          ".X..X.",
          ".X..X.",
          ".XXX.."),
    "C": ("..XXX.",
          ".X....",
          ".X....",
          ".X....",
          ".X....",
          "..XXX."),
    "D": (".XXX..",
          ".X..X.",
          ".X..X.",
          ".X..X.",
          ".X..X.",
          ".XXX.."),
    "E": (".XXXX.",
          ".X....",
          ".XXX..",
          ".X....",
          ".X....",
          ".XXXX."),
    "F": (".XXXX.",
          ".X....",
          ".XXX..",
          ".X....",
          ".X....",
          ".X...."),
    "G": ("..XXX.",
          ".X....",
          ".X....",
          ".X.XX.",
          ".X..X.",
          "..XXX."),
    "H": (".X..X.",
          ".X..X.",
          ".XXXX.",
          ".X..X.",
          ".X..X.",
          ".X..X."),
    "I": (".XXXX.",
          "..XX..",
          "..XX..",
          "..XX..",
          "..XX..",
          ".XXXX."),
    "J": ("...XX.",
          "....X.",
          "....X.",
          "....X.",
          ".X..X.",
          "..XX.."),
    "K": (".X..X.",
          ".X.X..",
          ".XX...",
          ".XX...",
          ".X.X..",
          ".X..X."),
    "L": (".X....",
          ".X....",
          ".X....",
          ".X....",
          ".X....",
          ".XXXX."),
    "M": ("X...X.",
          "XX.XX.",
          "X.X.X.",
          "X...X.",
          "X...X.",
          "X...X."),
    "N": ("X...X.",
          "XX..X.",
          "X.X.X.",
          "X..XX.",
          "X...X.",
          "X...X."),
    "O": ("..XX..",
          ".X..X.",
          ".X..X.",
          ".X..X.",
          ".X..X.",
          "..XX.."),
    "P": (".XXX..",
          ".X..X.",
          ".X..X.",
          ".XXX..",
          ".X....",
          ".X...."),
    "Q": ("..XX..",
          ".X..X.",
          ".X..X.",
          ".X..X.",
          "..XX..",
          "...XX."),
    "R": (".XXX..",
          ".X..X.",
          ".X..X.",
          ".XXX..",
          ".X.X..",
          ".X..X."),
    "S": ("..XXX.",
          ".X....",
          "..XX..",
          "....X.",
          "....X.",
          ".XXX.."),
    "T": (".XXXX.",
          "..XX..",
          "..XX..",
          "..XX..",
          "..XX..",
          "..XX.."),
    "U": (".X..X.",
          ".X..X.",
          ".X..X.",
          ".X..X.",
          ".X..X.",
          "..XX.."),
    "V": ("X...X.",
          "X...X.",
          "X...X.",
          ".X.X..",
          ".X.X..",
          "..X..."),
    "W": ("X...X.",
          "X...X.",
          "X...X.",
          "X.X.X.",
          "XX.XX.",
          "X...X."),
    "X": ("X...X.",
          ".X.X..",
          "..X...",
          "..X...",
          ".X.X..",
          "X...X."),
    "Y": ("X...X.",
          ".X.X..",
          "..X...",
          "..X...",
          "..X...",
          "..X..."),
    "Z": ("XXXXX.",
          "...X..",
          "..X...",
          ".X....",
          "X.....",
          "XXXXX."),

    # --- lowercase -------------------------------------------------------
    # Bottom-justified: every lowercase glyph sits on row 5, the bottom row
    # of the block. Ascenders (b d f h k l t) are five rows tall and rise
    # higher than the x-height letters; descenders (g j p q y) keep their
    # tails on row 5 with their bodies one row higher, which is what makes
    # them read as descenders.
    "a": ("......",
          "......",
          "..XX..",
          ".X..X.",
          ".X..X.",
          "..XXX."),
    "b": ("......",
          ".X....",
          ".X....",
          ".XXX..",
          ".X..X.",
          ".XXX.."),
    "c": ("......",
          "......",
          "..XXX.",
          ".X....",
          ".X....",
          "..XXX."),
    "d": ("......",
          "....X.",
          "....X.",
          "..XXX.",
          ".X..X.",
          "..XXX."),
    "e": ("......",
          "......",
          "..XX..",
          ".XXXX.",
          ".X....",
          "..XXX."),
    "f": ("......",
          "..XX..",
          "..X...",
          ".XXX..",
          "..X...",
          "..X..."),
    "g": ("......",
          "..XXX.",
          ".X..X.",
          "..XXX.",
          "....X.",
          ".XXX.."),
    "h": ("......",
          ".X....",
          ".X....",
          ".XXX..",
          ".X..X.",
          ".X..X."),
    "i": ("......",
          "..X...",
          "......",
          "..X...",
          "..X...",
          "..X..."),
    "j": ("...X..",
          "......",
          "...X..",
          "...X..",
          "...X..",
          ".XX..."),
    "k": ("......",
          ".X....",
          ".X..X.",
          ".XXX..",
          ".X.X..",
          ".X..X."),
    "l": ("......",
          ".XX...",
          "..X...",
          "..X...",
          "..X...",
          "..XX.."),
    "m": ("......",
          "......",
          "XX.XX.",
          "X.X.X.",
          "X.X.X.",
          "X.X.X."),
    "n": ("......",
          "......",
          ".XXX..",
          ".X..X.",
          ".X..X.",
          ".X..X."),
    "o": ("......",
          "......",
          "..XX..",
          ".X..X.",
          ".X..X.",
          "..XX.."),
    "p": ("......",
          ".XXX..",
          ".X..X.",
          ".XXX..",
          ".X....",
          ".X...."),
    "q": ("......",
          "..XXX.",
          ".X..X.",
          "..XXX.",
          "....X.",
          "....X."),
    "r": ("......",
          "......",
          ".X.XX.",
          ".XX...",
          ".X....",
          ".X...."),
    "s": ("......",
          "......",
          "..XXX.",
          ".XX...",
          "...XX.",
          ".XXX.."),
    "t": ("......",
          "..X...",
          ".XXX..",
          "..X...",
          "..X...",
          "..XXX."),
    "u": ("......",
          "......",
          ".X..X.",
          ".X..X.",
          ".X..X.",
          "..XXX."),
    "v": ("......",
          "......",
          "X...X.",
          "X...X.",
          ".X.X..",
          "..X..."),
    "w": ("......",
          "......",
          "X...X.",
          "X...X.",
          "X.X.X.",
          ".X.X.."),
    "x": ("......",
          "......",
          ".X..X.",
          "..XX..",
          "..XX..",
          ".X..X."),
    "y": ("......",
          ".X..X.",
          ".X..X.",
          "..XXX.",
          "....X.",
          ".XXX.."),
    "z": ("......",
          "......",
          ".XXXX.",
          "...X..",
          "..X...",
          ".XXXX."),
    # --- digits ----------------------------------------------------------
    "0": ("..XX..",
          ".X..X.",
          ".X.XX.",
          ".XX.X.",
          ".X..X.",
          "..XX.."),
    "1": ("..XX..",
          ".XXX..",
          "..XX..",
          "..XX..",
          "..XX..",
          ".XXXX."),
    "2": ("..XX..",
          ".X..X.",
          "....X.",
          "..XX..",
          ".X....",
          ".XXXX."),
    "3": (".XXX..",
          "....X.",
          "..XX..",
          "....X.",
          "....X.",
          ".XXX.."),
    "4": ("...XX.",
          "..X.X.",
          ".X..X.",
          ".XXXX.",
          "....X.",
          "....X."),
    "5": (".XXXX.",
          ".X....",
          ".XXX..",
          "....X.",
          "....X.",
          ".XXX.."),
    "6": ("..XXX.",
          ".X....",
          ".XXX..",
          ".X..X.",
          ".X..X.",
          "..XX.."),
    "7": (".XXXX.",
          "....X.",
          "...X..",
          "..X...",
          "..X...",
          "..X..."),
    "8": ("..XX..",
          ".X..X.",
          "..XX..",
          ".X..X.",
          ".X..X.",
          "..XX.."),
    "9": ("..XX..",
          ".X..X.",
          ".X..X.",
          "..XXX.",
          "....X.",
          "..XX.."),

    # --- punctuation and symbols -----------------------------------------
    "!": ("..XX..",
          "..XX..",
          "..XX..",
          "..XX..",
          "......",
          "..XX.."),
    "?": ("..XX..",
          ".X..X.",
          "...X..",
          "..X...",
          "......",
          "..X..."),
    ".": ("......",
          "......",
          "......",
          "......",
          "..XX..",
          "..XX.."),
    ",": ("......",
          "......",
          "......",
          "..XX..",
          "..XX..",
          ".XX..."),
    ":": ("......",
          "..XX..",
          "..XX..",
          "......",
          "..XX..",
          "..XX.."),
    ";": ("......",
          "..XX..",
          "..XX..",
          "......",
          "..XX..",
          ".XX..."),
    "'": ("..XX..",
          "..XX..",
          "......",
          "......",
          "......",
          "......"),
    '"': (".X.X..",
          ".X.X..",
          "......",
          "......",
          "......",
          "......"),
    "-": ("......",
          "......",
          ".XXXX.",
          "......",
          "......",
          "......"),
    "_": ("......",
          "......",
          "......",
          "......",
          "......",
          "XXXXX."),
    "+": ("......",
          "..X...",
          "..X...",
          "XXXXX.",
          "..X...",
          "..X..."),
    "=": ("......",
          "......",
          ".XXXX.",
          "......",
          ".XXXX.",
          "......"),
    "*": ("......",
          ".X.X..",
          "..X...",
          ".X.X..",
          "......",
          "......"),
    "/": ("....X.",
          "....X.",
          "...X..",
          "..X...",
          ".X....",
          ".X...."),
    "\\": (".X....",
           ".X....",
           "..X...",
           "...X..",
           "....X.",
           "....X."),
    "(": ("...X..",
          "..X...",
          "..X...",
          "..X...",
          "..X...",
          "...X.."),
    ")": ("..X...",
          "...X..",
          "...X..",
          "...X..",
          "...X..",
          "..X..."),
    "<": ("....X.",
          "...X..",
          "..X...",
          "..X...",
          "...X..",
          "....X."),
    ">": ("..X...",
          "...X..",
          "....X.",
          "....X.",
          "...X..",
          "..X..."),
    "#": (".X.X..",
          "XXXXX.",
          ".X.X..",
          "XXXXX.",
          ".X.X..",
          "......"),
    "%": ("X...X.",
          "...X..",
          "..X...",
          ".X....",
          "X...X.",
          "......"),
    "&": ("..XX..",
          ".X..X.",
          "..XX..",
          ".XX.X.",
          ".X..X.",
          "..XX.X"),
    "@": ("..XX..",
          ".X..X.",
          ".X.XX.",
          ".X.XX.",
          ".X....",
          "..XXX."),
    "$": ("..XX..",
          ".XXXX.",
          ".XX...",
          "..XX..",
          ".XXXX.",
          "..XX.."),

    # Shown for any character with no glyph of its own.
    "\x00": ("XXXXXX",
             "X....X",
             "X....X",
             "X....X",
             "X....X",
             "XXXXXX"),
}

FALLBACK = GLYPHS["\x00"]


def get(ch):
    """Glyph for a character, falling back to a hollow box.

    Upper and lower case have distinct glyphs. A character with no glyph of
    its own is tried upper-cased before giving up, so anything cased still
    renders even if only one case is drawn.
    """
    return GLYPHS.get(ch, GLYPHS.get(ch.upper(), FALLBACK))


def supported():
    """Every character this font can render, as a sorted string."""
    return "".join(sorted(c for c in GLYPHS if c >= " "))


def unsupported(text):
    """Characters in text that would render as the fallback box."""
    return "".join(sorted({c for c in text
                           if c not in GLYPHS and c.upper() not in GLYPHS}))


def _validate():
    """Check every glyph is exactly HEIGHT rows of WIDTH columns."""
    bad = []
    for ch, g in GLYPHS.items():
        if len(g) != HEIGHT:
            bad.append("%r has %d rows" % (ch, len(g)))
        for i, row in enumerate(g):
            if len(row) != WIDTH:
                bad.append("%r row %d is %d wide: %r" % (ch, i, len(row), row))
    return bad


def preview(text):
    """Print glyphs side by side as ASCII -- runs on a laptop or the board."""
    glyphs = [get(c) for c in text]
    for y in range(HEIGHT):
        print(" ".join(g[y] for g in glyphs).replace(".", " ").replace("X", "#"))


if __name__ == "__main__":
    errors = _validate()
    if errors:
        print("FAIL")
        for e in errors:
            print("  ", e)
    else:
        print("all %d glyphs are %dx%d" % (len(GLYPHS), WIDTH, HEIGHT))
    print("supported:", supported())
    print()
    preview("Hello!")
    print()
    for row in ("abcdefghi", "jklmnopqr", "stuvwxyz?"):
        preview(row)
        print()
    preview("0123456789")
